[package]
name = "bellhop-client"
version = "0.2.1-dev"
authors = ["Sam Wilson <sawilson@akamai.com>"]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "1.5"
reqwest = { version = "~0.9", default-features = false }

[dev-dependencies]
