[workspace]
members = [
    "bellhop",
    "bellhop-bin",

    "bellhop-hook-jenkins",
    "bellhop-hook-email",

    "bellhop-auth-dummy",
    "bellhop-auth-header",
]
default-members = ["bellhop-bin"]
