/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AssetType {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "plural_name")]
    pub plural_name: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl AssetType {
    pub fn new(id: i32, plural_name: String, name: String) -> AssetType {
        AssetType {
            id: id,
            plural_name: plural_name,
            name: name,
        }
    }
}
