/* 
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Assets {
  #[serde(rename = "items")]
  items: Vec<::models::Asset>,
  #[serde(rename = "pages")]
  pages: ::models::Pages
}

impl Assets {
  pub fn new(items: Vec<::models::Asset>, pages: ::models::Pages) -> Assets {
    Assets {
      items: items,
      pages: pages
    }
  }

  pub fn set_items(&mut self, items: Vec<::models::Asset>) {
    self.items = items;
  }

  pub fn with_items(mut self, items: Vec<::models::Asset>) -> Assets {
    self.items = items;
    self
  }

  pub fn items(&self) -> &Vec<::models::Asset> {
    &self.items
  }


  pub fn set_pages(&mut self, pages: ::models::Pages) {
    self.pages = pages;
  }

  pub fn with_pages(mut self, pages: ::models::Pages) -> Assets {
    self.pages = pages;
    self
  }

  pub fn pages(&self) -> &::models::Pages {
    &self.pages
  }


}



