/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Asset {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "type_id")]
    pub type_id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "lease_id")]
    pub lease_id: Option<i32>,
}

impl Asset {
    pub fn new(id: i32, type_id: i32, name: String, lease_id: Option<i32>) -> Asset {
        Asset {
            id: id,
            type_id: type_id,
            name: name,
            lease_id: lease_id,
        }
    }
}
