/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateTag {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "tag_type_id")]
    pub tag_type_id: i32,
}

impl CreateTag {
    pub fn new(value: String, tag_type_id: i32) -> CreateTag {
        CreateTag {
            value: value,
            tag_type_id: tag_type_id,
        }
    }
}
