/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateAsset {
    #[serde(rename = "type_id")]
    pub type_id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "lease_id", skip_serializing_if = "Option::is_none")]
    pub lease_id: Option<i32>,
}

impl CreateAsset {
    pub fn new(type_id: i32, name: String) -> CreateAsset {
        CreateAsset {
            type_id: type_id,
            name: name,
            lease_id: None,
        }
    }
}
