/* 
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct CreateAssetType {
  #[serde(rename = "name")]
  name: String,
  #[serde(rename = "plural_name")]
  plural_name: String
}

impl CreateAssetType {
  pub fn new(name: String, plural_name: String) -> CreateAssetType {
    CreateAssetType {
      name: name,
      plural_name: plural_name
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> CreateAssetType {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }


  pub fn set_plural_name(&mut self, plural_name: String) {
    self.plural_name = plural_name;
  }

  pub fn with_plural_name(mut self, plural_name: String) -> CreateAssetType {
    self.plural_name = plural_name;
    self
  }

  pub fn plural_name(&self) -> &String {
    &self.plural_name
  }


}



