/* 
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Pages {
  #[serde(rename = "next")]
  next: Option<String>,
  #[serde(rename = "prev")]
  prev: Option<String>,
}

impl Pages {
  pub fn new(next: Option<String>, prev: Option<String>) -> Pages {
    Pages {
      next: next,
      prev: prev
    }
  }

  pub fn set_next(&mut self, next: String) {
    self.next = Some(next);
  }

  pub fn with_next(mut self, next: String) -> Pages {
    self.next = Some(next);
    self
  }

  pub fn next(&self) -> Option<&String> {
    self.next.as_ref()
  }


  pub fn set_prev(&mut self, prev: String) {
    self.prev = Some(prev);
  }

  pub fn with_prev(mut self, prev: String) -> Pages {
    self.prev = Some(prev);
    self
  }

  pub fn prev(&self) -> Option<&String> {
    self.prev.as_ref()
  }


}



