/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Tag {
    #[serde(rename = "asset_id")]
    pub asset_id: i32,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "tag_type_id")]
    pub tag_type_id: i32,
}

impl Tag {
    pub fn new(asset_id: i32, value: String, tag_type_id: i32) -> Tag {
        Tag {
            asset_id: asset_id,
            value: value,
            tag_type_id: tag_type_id,
        }
    }
}
