/* 
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Tag {
  #[serde(rename = "asset_id")]
  asset_id: i32,
  #[serde(rename = "value")]
  value: String,
  #[serde(rename = "tag_type_id")]
  tag_type_id: i32
}

impl Tag {
  pub fn new(asset_id: i32, value: String, tag_type_id: i32) -> Tag {
    Tag {
      asset_id: asset_id,
      value: value,
      tag_type_id: tag_type_id
    }
  }

  pub fn set_asset_id(&mut self, asset_id: i32) {
    self.asset_id = asset_id;
  }

  pub fn with_asset_id(mut self, asset_id: i32) -> Tag {
    self.asset_id = asset_id;
    self
  }

  pub fn asset_id(&self) -> &i32 {
    &self.asset_id
  }


  pub fn set_value(&mut self, value: String) {
    self.value = value;
  }

  pub fn with_value(mut self, value: String) -> Tag {
    self.value = value;
    self
  }

  pub fn value(&self) -> &String {
    &self.value
  }


  pub fn set_tag_type_id(&mut self, tag_type_id: i32) {
    self.tag_type_id = tag_type_id;
  }

  pub fn with_tag_type_id(mut self, tag_type_id: i32) -> Tag {
    self.tag_type_id = tag_type_id;
    self
  }

  pub fn tag_type_id(&self) -> &i32 {
    &self.tag_type_id
  }


}



