/*
 * Bellhop
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TagType {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "asset_type_id")]
    pub asset_type_id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "detail_only")]
    pub detail_only: bool,
    #[serde(rename = "rightness")]
    pub rightness: i32,
}

impl TagType {
    pub fn new(
        id: i32,
        asset_type_id: i32,
        name: String,
        detail_only: bool,
        rightness: i32,
    ) -> TagType {
        TagType {
            id: id,
            asset_type_id: asset_type_id,
            name: name,
            detail_only: detail_only,
            rightness: rightness,
        }
    }
}
